### ISSUE TITLE
Intermittent failure in test_do_layout

### ISSUE THREAD

**Issue by mdickinson** [enthought/graphcanvas#32]
The following failure was spotted in a Travis CI run: (https://app.travis-ci.com/github/enthought/graphcanvas/builds/234724835), during the run for the pyqt (i.e., Qt 4) toolkit, on PR #31. It looks as though there may be some source of indeterminacy in the test run.

```
======================================================================
FAIL: test_do_layout (graphcanvas.tests.test_graph_container.TestGraphContainer)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/.edm/envs/graphcanvas-test-3.6-pyqt/lib/python3.6/site-packages/graphcanvas/tests/test_graph_container.py", line 58, in test_do_layout
    self.assert_in_bounds(container)
  File "/home/travis/.edm/envs/graphcanvas-test-3.6-pyqt/lib/python3.6/site-packages/graphcanvas/tests/test_graph_container.py", line 36, in assert_in_bounds
    self.assertGreaterEqual(component.x, lower_x)
AssertionError: -2.842170943040401e-14 not greater than or equal to 0
```

**Comment by mdickinson** [comment]
Another occurrence of this in the weekly cron job: https://github.com/enthought/graphcanvas/runs/3563035155?check_suite_focus=true
```
======================================================================
FAIL: test_do_layout (graphcanvas.tests.test_graph_container.TestGraphContainer)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/.edm/envs/graphcanvas-test-3.6-pyside2/lib/python3.6/site-packages/graphcanvas/tests/test_graph_container.py", line 58, in test_do_layout
    self.assert_in_bounds(container)
  File "/home/runner/.edm/envs/graphcanvas-test-3.6-pyside2/lib/python3.6/site-packages/graphcanvas/tests/test_graph_container.py", line 36, in assert_in_bounds
    self.assertGreaterEqual(component.x, lower_x)
AssertionError: -2.842170943040401e-14 not greater than or equal to 0
```

The cron job passed on a re-run.
